### ISSUE TITLE
Get commands

### ISSUE THREAD

**Issue by captainsalt** [Auxes/Discord.Net-Example#1]
Hello Auxes,

 If you could make a module displaying how to properly get commands and display information about them like their aliases and such that would be awesome. 

Thanks,

**Comment by captainsalt** [comment]
Whoops, this isn't the 1.0 repo

**Comment by Aux** [comment]
Issues are for the entire repo, not just a specific branch ;)

**Comment by Aux** [comment]
Resolved and only took way longer than necessary.
