### ISSUE TITLE
Program does not contain a static 'Main' method suitable for entry point

### ISSUE THREAD

**Issue by trigger-segfault** [Auxes/Discord.Net-Example#10]
Visual Studio 2017 doesn't like that `Main` returns a `Task` and throws this error during compile. I'm not sure how I should be modifying the Main method since you set it up to return a task.

**Comment by NeonPhoenix** [comment]
I had a similar issue today, however I went into my project Properties > Build > Advanced and changed language version to C# 7.2.
After that my program starting working again.

**Comment by Aux** [comment]
Resolved per 36fafbd15b199f484b2d1ecce17d2d4eca2ba863 and #12
