### ISSUE TITLE
No service for type 'CommandHandler'

### ISSUE THREAD

**Issue by NeonPhoenix** [Auxes/Discord.Net-Example#11]
Run into `System.InvalidOperationException` while trying to run code.
Program breaks a `provider.GetRequiredService<CommandHandler>();`

Solution:
Add `.AddSingleton<CommandHandler>()` to `ConfigureServices`

**Comment by Aux** [comment]
Resolved per 5a82e606e346520d343d73934b2c715d8b872dca
