### ISSUE TITLE
Visual Studio Packages

### ISSUE THREAD

**Issue by Jytesh** [Auxes/Discord.Net-Example#13]
Could you specify the packages I need to add in VS17 for this?

**Comment by Aux** [comment]
You can see the nuget packages this project uses in the [csproj file](https://github.com/Aux/Discord.Net-Example/blob/2.0/src/Discord.Net-Example.csproj). If you're asking about nuget sources instead, the only potential external source would be the [dnet myget source](https://github.com/discord-net/Discord.Net#unstable-myget).

**Comment by Jytesh** [comment]
The csproj was builded and is running succefully but the bot won't come online i added my token in quotes in the yml file any idea why it is not working?

**Comment by Braythor** [comment]
@Jytesh did you put in your token or your client ID?

**Comment by Jytesh** [comment]
> @Jytesh did you put in your token or your client ID?

I put token in token. No i didn't put any Client ID.
