### ISSUE TITLE
UnknownCommand: Unknown command.

### ISSUE THREAD

**Issue by Voidoz** [Auxes/Discord.Net-Example#21]
This happens for all commands and I've copied and pasted the code into my project and am wondering where I should look in the code to solve this issue. Of course, I did read where you have the error being output into the Discord channel but really that didn't help me know where it's having an issue getting the command modules. 

Of course, since I don't know where the issue is, please tell me what code I should share to resolve this.

Thanks

**Comment by Aux** [comment]
You copying code into your own project is not an issue with this project. If you have any questions about the Discord.Net library you need to ask in their spaces.
