### ISSUE TITLE
Random is not thread safe.

### ISSUE THREAD

**Issue by ghost** [Auxes/Discord.Net-Example#3]
The singleton should be a `ThreadLocal<Random>` or maybe a Random with a lock mechanism. Using only one instance on multiple threads will result in getting 0 from every Random call, has happened to me in the past.

**Comment by Aux** [comment]
Thank you for your concern, but this is a basic example of a bot with discord.net. If someone is planning on having a bot large enough for this to become an issue, they should have the ability to diagnose and fix it in their own project. For it's intended usage, this snippet is fine as is.
