### ISSUE TITLE
Solution won't run

### ISSUE THREAD

**Issue by Wllew4** [Auxes/Discord.Net-Example#8]
![image](https://user-images.githubusercontent.com/29740388/35124002-7f7b6696-fc72-11e7-8b05-22889b4487ef.png)
I get this error every time I try to run the program from visual studio. Does anyone know why?

**Comment by KeithPetro** [comment]
This is seemingly a conflict between different versions of dotnet.exe. See: https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/162

**Comment by Aux** [comment]
Hopefully you've solved this by now :'(
